version: "3.7"
services:
  teachback:
    image: us.gcr.io/gcp101233-lv61301devops/646/teachback:latest
    # container_name: teachback
    restart: unless-stopped
    environment:
      main_ip: 34.69.223.68
    ports:
    - 8283-8284:8080
  teachfront:
    image: us.gcr.io/gcp101233-lv61301devops/646/teachfront:latest
    #container_name: teachfront
    restart: unless-stopped
    command: sh -c "/teachfront/run.sh"
    environment:
      main_ip: 34.123.64.22
    ports:
    - 8292-8293:3000 
    depends_on:
    - teachback
  nginx: 
    image: us.gcr.io/gcp101233-lv61301devops/646/nginx:latest
    container_name: nginx
    restart: always
    ports:
    - 8282:80 
    volumes:  
    - ./default.conf:/etc/nginx/conf.d/default.conf
      #depends_on:
      #- teachback
      #- teachfront

  nginxfront:
    image: us.gcr.io/gcp101233-lv61301devops/646/nginx:latest
    container_name: nginxfront
    restart: always
    ports:
    - 8289:80
    volumes:
    - ./defaultfront.conf:/etc/nginx/conf.d/default.conf
    
  node_exporter:
    image: us.gcr.io/gcp101233-lv61301devops/646/monitoring/nodexporter:latest
    container_name: node_exporter
    restart: unless-stopped
    ports:
    - 5555:9100
  cadvisor:
    image: us.gcr.io/gcp101233-lv61301devops/646/monitoring/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    # expose:
    # - 1234
    ports:
    - 1234:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro